name: Deploy Shopify Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Shopify
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Shopify CLI
        run: npm install -g @shopify/cli@latest @shopify/theme@latest

      - name: Deploy Theme
        env:
          SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_STORE_URL }}
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
        run: |
          shopify theme push \
            --theme ${{ secrets.SHOPIFY_THEME_ID }} \
            --allow-live \
            --ignore "assets/*.mp4" \
            --ignore "assets/*.mov" \
            --ignore "assets/*.webm" \
            --json
